# fly.toml app configuration file generated for badtranslator on 2023-06-08T19:30:13+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "badtranslator"
primary_region = "arn"

[build]
  image = "badtranslator"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
